pipeline:
  type: chain
  transforms:
    - type: MatchContinuously
      input: {}
      config:
        file_pattern: "gs://zero-copy-parquet-dir/*.parquet"
        interval: 10
    - type: MapToFields
      config:
        language: python
        fields:
          path:
            callable: "lambda metadata: metadata.path"
            output_type: string
    - type: LogForTesting
    - type: IcebergAddFiles
      config:
        table: "my_db.dest_streaming_table"
        triggering_frequency_seconds: 10
        catalog_properties:
          type: "rest"
          uri: "https://biglake.googleapis.com/iceberg/v1/restcatalog"
          warehouse: "gs://zero-copy-warehouse"
          header.x-goog-user-project: "apache-beam-testing"
          rest.auth.type: "google"
          io-impl: "org.apache.iceberg.gcp.gcs.GCSFileIO"
          rest-metrics-reporting-enabled: "false"
        error_handling:
          output: errors
    - type: LogForTesting
      input: IcebergAddFiles.errors

providers:
  - type: python
    config: {}
    transforms:
      MatchContinuously: 'apache_beam.io.fileio.MatchContinuously'
